// MobileDevicesQuestions

const mobileDevicesQuestions =[
    {question: “Your company’s executives are concerned about employees using personal devices for work purposes. They are concerned that someone will leave and take proprietary information with them. By informing them about the presence of protective measures to safeguard company data accessed by employees, you alleviate their concerns. What are these protective measures commonly referred to as?”, 
    option_A: ‘GSM’, 
    option_B: ‘CDMA’, 
    option_C: ‘MAM’, 
    option_D: ‘MDM’, 
    answer_1: ‘MDM’, 
    answer_2: ‘MAM’, 
    answer_3: ‘’, 
    explanation: ‘’,
    topic: ‘mobile devices’, 
    subtopic: ‘Network connectivity & support’,
    Id: ‘1’  },
    
    {question: “You’re setting up private email on a coworker’s phone. He wants to ensure that all of his mail is stored solely on their phone. Which mail protocol stores all emails on a single device to access them?”,
    option_A: ‘S/MIME’,
    option_B: ‘POP3’,
    option_C: ‘SMTP’, 
    option_D: ‘IMAP’, 
    answer_1:’POP3’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘2’ },
    
    {question: “A friend of yours who isn’t particularly tech-adept recently bought a touch pen with Bluetooth connectivity. You have offered to set it up for him. After the laptop has found the touch pen for pairing, what step of the Bluetooth connection process will you take?”,
    option_A: ‘Enable Bluetooth’,
    option_B: ‘Enter the appropriate PIN code’,
    option_C: ‘Enable Pairing’, 
    option_D: ‘Test connectivity’, 
    answer_1:’Enter the appropriate PIN code’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘3’ },
    
    {question: ”You’re setting up company email on a colleague’s phone. The company must keep a copy of every email on their server, even after the user has accessed it. Which of the following mail protocols stores all emails on the server and allows messages to be synchronized across multiple devices?”,
    option_A: ‘SMTP’,
    option_B: ‘POP3’,
    option_C: ‘S/MIME’, 
    option_D: ‘IMAP’, 
    answer_1:’IMAP’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘4’ },
    
    {question: “What technology allows you to reduce the number of times a user needs log in for numerous services?”,
    option_A: ‘Nonrepudiation’,
    option_B: ‘SSO’,
    option_C: ‘SMTP’, 
    option_D: ‘Synchronization’, 
    answer_1:’SSO’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘5’ },
    
    {question: “Employees at your company are permitted to use their personal devices for work-related purposes. As the IT director, what are the two things that you use to guarantee the security of the company’s data on those personal devices? “,
    option_A: ‘GSM’,
    option_B: ‘PRL’,
    option_C: ‘MAM’, 
    option_D: ‘MDM’, 
    answer_1:’MAM’, 
    answer_2: ‘MDM’, 
    answer_3: ‘’.
    Explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘6’ },
    
    {question: “You’re going hiking in unfamiliar territory this weekend and have downloaded an app on your phone that shows you where you are on the map in relation to the trails and surrounding areas. Which types of location technology could this app employ?”,
    option_A: ‘MDM’,
    option_B: ‘Cellular location services’,
    option_C: ‘RFID’, 
    option_D: ‘GPS’, 
    answer_1:’Cellular location services’, 
    answer_2: ‘GPS’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘7’ },
    
    {question: “You pay a premium for a faster internet connection at home. However, you’ve observed that download times have slowed down significantly and the spinning wheel appears more often than usual. What is the problem here?”,
    option_A: ‘You have reached a data cap’,
    option_B: “You’re synchronizing too much data all at once”’,
    option_C: “You didn’t pay your last bill, so they’re slowing the service down”, 
    option_D: ‘The internet is down’, 
    answer_1:’You have reached a data cap’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘8’ },
    
    {question: “What is the hosted messaging version of Microsoft’s Exchange mail server that stores email for customers off-site?”,
    option_A: ‘IExchange’,
    option_B: ‘Exchange Online’,
    option_C: ‘On-Prem Exchange’, 
    option_D: ‘Google Inbox’, 
    answer_1:’Exchange Online’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘9’ },
    
    {question: “Your significant other just bought a new car and wants you to set up their cell phone to use voice commands in the car. You must initiate pairing on your phone and select the option to look for pairing devices in your vehicle. What protocol are the automobile and the device using?”,
    option_A: ‘Lightning’,
    option_B: ‘Bluetooth’,
    option_C: ‘802.11a’, 
    option_D: ‘Wi-Fi Enabled’, 
    answer_1:’Bluetooth’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘10’ },
    
    {question: “____ is the unique mobile number that will identify you as a user. It is coded into the SIM card if you’re on a GSM network, or otherwise linked to your account, so that you can switch from one phone to another.”,
    option_A: ‘IMEI’,
    option_B: ‘PRI’,
    option_C: ‘MAC’, 
    option_D: ‘IMSI’, 
    answer_1:’IMSI’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘11’ },
    
    {question: “One user angrily tells you that her new Bluetooth headset is not working, then asks for your help. What is the MOST LIKELY cause of this issue?”,
    option_A: ‘The earpiece is broken’,
    option_B: ‘Bluetooth connectivity is lost’,
    option_C: ‘The Wi-Fi signal is weak’, 
    option_D: ‘The earpiece has paired to a different device’, 
    answer_1:’Bluetooth connectivity is lost’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘12’ },
    
    {question: “One of your employees has bought an external Bluetooth trackpad to use with her tablet. She then asks you to help her install and configure it. What steps will you have to take?”,
    option_A: ‘Put the device in pairing more and open Bluetooth settings on the tablet, then tap the trackpad’,
    option_B: ‘Install drivers.’,
    option_C: ‘Plug the device into a USB port.’, 
    option_D: ‘Go to Settings to configure speed and scrolling features.’, 
    answer_1:’Go to Settings to configure speed and scrolling features.’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘13’ },
    
    {question: “What will be the next step once you have enabled your device to communicate using the IEEE 802.15.1 standard?”,
    option_A: ‘Enable pairing.’,
    option_B: ‘Open port 802.15.1.’,
    option_C: ‘Find a device for pairing.’, 
    option_D: ‘Enter the PIN code.’, 
    answer_1:’Enable pairing.’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘14’ },
    
    {question: “Long-Term Evolution (LTE) is also known as ______ cellular communication technology.”,
    option_A: ‘5G’,
    option_B: ‘3G’,
    option_C: ‘4G’, 
    option_D: ‘2G’, 
    answer_1:’4G’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘15’ },
    
    {question: “Which GSM system number is hard-coded into the phone and identifies your physical phone hardware to the cellular tower?”,
    option_A: ‘MAC.’,
    option_B: ‘IMSI.’,
    option_C: ‘PRI.’, 
    option_D: ‘IMEI.’, 
    answer_1:’IMEI.’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘16’ },
    
    {question: “You’ve turned on Bluetooth on both your new headset and your laptop, as well as enabled pairing on both. They’ve found each other, so what;s the next step?”,
    option_A: ‘Entering the Bluetooth password.’,
    option_B: ‘Entering the Bluetooth PIN code.’,
    option_C: ‘Pressing and holding a Bluetooth button.’, 
    option_D: ‘Exiting out of any running Bluetooth applications.’, 
    answer_1:’Entering the Bluetooth PIN code.’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘17’ },
    
    {question: “In order to avoid getting lost when hiking in the mountains, you have taken with you a mobile device with an app that has all the maps of the local trails. When you look at the map, you see that the blue dot indicating your location hasn’t moved since you left your house. Which setting on your mobile device must be enabled for the app to function properly?”,
    option_A: ‘GPS.’,
    option_B: ‘Airplane mode.’,
    option_C: ‘Location services.’, 
    option_D: ‘Wi-Fi.’, 
    answer_1:’Location services.’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘18’ },
    
    {question: “You’ve turned on the GPS service on your tablet. What is the minimum of GPS satellites with which your tablet must communicate in order to determine its location?”,
    option_A: ‘Four.’,
    option_B: ‘Two.’,
    option_C: ‘Three.’, 
    option_D: ‘One.’, 
    answer_1:’Three.’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘19’ },
    
    {question: “You’re putting in Bluetooth speakers in a conference room and have just entered the pin to link the two devices. What will be your next step?”,
    option_A: ‘Enable pairing.’,
    option_B: ‘Enable Bluetooth.’,
    option_C: ‘Search for the Bluetooth device.’, 
    option_D: ‘Test connectivity.’, 
    answer_1:’Test connectivity.’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘20’ },
    
    {question: “What kind of updates are delivered to mobile devices over the air?”,
    option_A: ‘IMEI.’,
    option_B: ‘PRI and PRL.’,
    option_C: ‘Screen resolution.’, 
    option_D: ‘IMSI.’, 
    answer_1:’PRI and PRL.’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘21’ },
    
    {question: “Your coworker wants to utilize maps on his phone but he is concerned that other apps are also tracking his real locations. Then he asks for your help. WHich of the following statements is FALSE?”,
    option_A: ‘You can turn location services on or off for applications in the settings of your device.’,
    option_B: “When you’re installing an application, most likely it will ask you when it is allowed to use location services.”,
    option_C: ‘If location services are turned off for one purpose, they are turned off for all services.’, 
    option_D: ‘Some applications won’t work without location services.’, 
    Answer_1: ‘If location services are turned off for one purpose, they are turned off for all services., 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘22’ },
    
    {question: “”,
    option_A: ‘’,
    option_B: ‘’,
    option_C: ‘’, 
    option_D: ‘’, 
    answer_1:’’, 
    answer_2: ‘’, 
    answer_3: ‘’.
    explanation: ‘’, 
    topic: ‘mobile devices’,
    subtopic: ‘Network connectivity & support’,
    id: ‘’ },
    
    ];
    
    
    Export default {mobileDevices :  mobileDevicesQuestions};
    
    
    
    